// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countUnusedRecoveryCodes = `-- name: CountUnusedRecoveryCodes :one
SELECT count(*) FROM recovery_codes WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) CountUnusedRecoveryCodes(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnusedRecoveryCodes, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCredentials = `-- name: CreateCredentials :exec
INSERT INTO credentials (user_id, password_hash) VALUES ($1, $2)
`

type CreateCredentialsParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) CreateCredentials(ctx context.Context, arg CreateCredentialsParams) error {
	_, err := q.db.Exec(ctx, createCredentials, arg.UserID, arg.PasswordHash)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (username, name) VALUES ($1::text, $2::text)
RETURNING id, username, name, created_at
`

type CreateUserParams struct {
	Username string `json:"username"`
	Name     string `json:"name"`
}

type CreateUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Username, arg.Name)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getCredentialsForUpdate = `-- name: GetCredentialsForUpdate :one
SELECT password_hash, failed_attempts, locked_until FROM credentials WHERE user_id = $1 FOR UPDATE
`

type GetCredentialsForUpdateRow struct {
	PasswordHash   string             `json:"password_hash"`
	FailedAttempts int32              `json:"failed_attempts"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
}

func (q *Queries) GetCredentialsForUpdate(ctx context.Context, userID uuid.UUID) (GetCredentialsForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getCredentialsForUpdate, userID)
	var i GetCredentialsForUpdateRow
	err := row.Scan(&i.PasswordHash, &i.FailedAttempts, &i.LockedUntil)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, expires_at, revoked_at FROM refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

type GetRefreshTokenForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, username, name, created_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, name, created_at FROM users WHERE lower(username) = lower($1::text) AND deleted_at IS NULL
`

type GetUserByUsernameRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (GetUserByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i GetUserByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const insertRecoveryCode = `-- name: InsertRecoveryCode :exec
INSERT INTO recovery_codes (user_id, code_hash) VALUES ($1, $2)
`

type InsertRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
}

func (q *Queries) InsertRecoveryCode(ctx context.Context, arg InsertRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, insertRecoveryCode, arg.UserID, arg.CodeHash)
	return err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE credentials SET
    failed_attempts = CASE WHEN failed_attempts + 1 >= $1::int THEN 0 ELSE failed_attempts + 1 END,
    locked_until = CASE WHEN failed_attempts + 1 >= $1::int THEN now() + make_interval(secs => $2::float8) ELSE locked_until END
WHERE user_id = $3
`

type RecordLoginFailureParams struct {
	MaxAttempts int32     `json:"max_attempts"`
	LockSecs    float64   `json:"lock_secs"`
	UserID      uuid.UUID `json:"user_id"`
}

// После max_attempts подряд неудач вход блокируется на lock_for; счётчик сбрасывается при блокировке.
func (q *Queries) RecordLoginFailure(ctx context.Context, arg RecordLoginFailureParams) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, arg.MaxAttempts, arg.LockSecs, arg.UserID)
	return err
}

const resetLoginFailures = `-- name: ResetLoginFailures :exec
UPDATE credentials SET failed_attempts = 0, locked_until = NULL WHERE user_id = $1
`

func (q *Queries) ResetLoginFailures(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, resetLoginFailures, userID)
	return err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const setPassword = `-- name: SetPassword :exec
UPDATE credentials SET password_hash = $2, failed_attempts = 0, locked_until = NULL, updated_at = now() WHERE user_id = $1
`

type SetPasswordParams struct {
	UserID       uuid.UUID `json:"user_id"`
	PasswordHash string    `json:"password_hash"`
}

func (q *Queries) SetPassword(ctx context.Context, arg SetPasswordParams) error {
	_, err := q.db.Exec(ctx, setPassword, arg.UserID, arg.PasswordHash)
	return err
}

const transferOwnedLists = `-- name: TransferOwnedLists :exec
WITH new_owner AS (
    SELECT DISTINCT ON (lm.list_id) lm.list_id, lm.user_id
    FROM list_members lm
    JOIN lists l ON l.id = lm.list_id
    WHERE l.owner_id = $1 AND lm.user_id <> $1
    ORDER BY lm.list_id, lm.joined_at
), moved AS (
    UPDATE lists l SET owner_id = n.user_id
    FROM new_owner n WHERE l.id = n.list_id
    RETURNING l.id AS list_id, n.user_id
)
UPDATE list_members lm SET role = 'owner'
FROM moved WHERE lm.list_id = moved.list_id AND lm.user_id = moved.user_id
`

// Перед удалением аккаунта: списки, где есть другие участники, переходят самому раннему из них.
func (q *Queries) TransferOwnedLists(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, transferOwnedLists, ownerID)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2 WHERE id = $1 AND deleted_at IS NULL
RETURNING id, username, name, created_at
`

type UpdateUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type UpdateUserNameRow struct {
	ID        uuid.UUID          `json:"id"`
	Username  string             `json:"username"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i UpdateUserNameRow
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const useRecoveryCode = `-- name: UseRecoveryCode :one
UPDATE recovery_codes SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
RETURNING id
`

type UseRecoveryCodeParams struct {
	UserID   uuid.UUID `json:"user_id"`
	CodeHash string    `json:"code_hash"`
}

// Помечает код использованным; пусто, если кода нет или он уже использован.
func (q *Queries) UseRecoveryCode(ctx context.Context, arg UseRecoveryCodeParams) (int64, error) {
	row := q.db.QueryRow(ctx, useRecoveryCode, arg.UserID, arg.CodeHash)
	var id int64
	err := row.Scan(&id)
	return id, err
}
