// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLoginCode = `-- name: CreateLoginCode :exec
INSERT INTO login_codes (email, code_hash, expires_at) VALUES (lower($3::text), $1, $2)
`

type CreateLoginCodeParams struct {
	CodeHash  string             `json:"code_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Email     string             `json:"email"`
}

func (q *Queries) CreateLoginCode(ctx context.Context, arg CreateLoginCodeParams) error {
	_, err := q.db.Exec(ctx, createLoginCode, arg.CodeHash, arg.ExpiresAt, arg.Email)
	return err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, expires_at) VALUES ($1, $2, $3)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const deleteExpiredLoginCodes = `-- name: DeleteExpiredLoginCodes :exec
DELETE FROM login_codes WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredLoginCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredLoginCodes)
	return err
}

const deleteLoginCodesByEmail = `-- name: DeleteLoginCodesByEmail :exec
DELETE FROM login_codes WHERE email = lower($1::text)
`

func (q *Queries) DeleteLoginCodesByEmail(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, deleteLoginCodesByEmail, email)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getActiveLoginCodeForUpdate = `-- name: GetActiveLoginCodeForUpdate :one
SELECT id, code_hash, attempts FROM login_codes
WHERE email = lower($1::text) AND expires_at > now()
ORDER BY created_at DESC LIMIT 1
FOR UPDATE
`

type GetActiveLoginCodeForUpdateRow struct {
	ID       int64  `json:"id"`
	CodeHash string `json:"code_hash"`
	Attempts int32  `json:"attempts"`
}

func (q *Queries) GetActiveLoginCodeForUpdate(ctx context.Context, email string) (GetActiveLoginCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getActiveLoginCodeForUpdate, email)
	var i GetActiveLoginCodeForUpdateRow
	err := row.Scan(&i.ID, &i.CodeHash, &i.Attempts)
	return i, err
}

const getRefreshTokenForUpdate = `-- name: GetRefreshTokenForUpdate :one
SELECT id, user_id, expires_at, revoked_at FROM refresh_tokens WHERE token_hash = $1 FOR UPDATE
`

type GetRefreshTokenForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) GetRefreshTokenForUpdate(ctx context.Context, tokenHash string) (GetRefreshTokenForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenForUpdate, tokenHash)
	var i GetRefreshTokenForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ExpiresAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, name, created_at FROM users WHERE id = $1 AND deleted_at IS NULL
`

type GetUserRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (GetUserRow, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i GetUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const incrementLoginCodeAttempts = `-- name: IncrementLoginCodeAttempts :exec
UPDATE login_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) IncrementLoginCodeAttempts(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementLoginCodeAttempts, id)
	return err
}

const insertEmailIdentity = `-- name: InsertEmailIdentity :exec
INSERT INTO auth_identities (user_id, provider, provider_uid)
VALUES ($1, 'email', lower($2::text))
ON CONFLICT DO NOTHING
`

type InsertEmailIdentityParams struct {
	UserID uuid.UUID `json:"user_id"`
	Email  string    `json:"email"`
}

func (q *Queries) InsertEmailIdentity(ctx context.Context, arg InsertEmailIdentityParams) error {
	_, err := q.db.Exec(ctx, insertEmailIdentity, arg.UserID, arg.Email)
	return err
}

const latestLoginCodeCreatedAt = `-- name: LatestLoginCodeCreatedAt :one
SELECT created_at FROM login_codes WHERE email = lower($1::text) ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) LatestLoginCodeCreatedAt(ctx context.Context, email string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, latestLoginCodeCreatedAt, email)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const revokeAllUserRefreshTokens = `-- name: RevokeAllUserRefreshTokens :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserRefreshTokens, userID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, id)
	return err
}

const revokeRefreshTokenByHash = `-- name: RevokeRefreshTokenByHash :exec
UPDATE refresh_tokens SET revoked_at = now() WHERE token_hash = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeRefreshTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshTokenByHash, tokenHash)
	return err
}

const transferOwnedLists = `-- name: TransferOwnedLists :exec
WITH new_owner AS (
    SELECT DISTINCT ON (lm.list_id) lm.list_id, lm.user_id
    FROM list_members lm
    JOIN lists l ON l.id = lm.list_id
    WHERE l.owner_id = $1 AND lm.user_id <> $1
    ORDER BY lm.list_id, lm.joined_at
), moved AS (
    UPDATE lists l SET owner_id = n.user_id
    FROM new_owner n WHERE l.id = n.list_id
    RETURNING l.id AS list_id, n.user_id
)
UPDATE list_members lm SET role = 'owner'
FROM moved WHERE lm.list_id = moved.list_id AND lm.user_id = moved.user_id
`

// Перед удалением аккаунта: списки, где есть другие участники, переходят самому раннему из них.
func (q *Queries) TransferOwnedLists(ctx context.Context, ownerID uuid.UUID) error {
	_, err := q.db.Exec(ctx, transferOwnedLists, ownerID)
	return err
}

const updateUserName = `-- name: UpdateUserName :one
UPDATE users SET name = $2 WHERE id = $1 AND deleted_at IS NULL
RETURNING id, email, name, created_at
`

type UpdateUserNameParams struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type UpdateUserNameRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpdateUserName(ctx context.Context, arg UpdateUserNameParams) (UpdateUserNameRow, error) {
	row := q.db.QueryRow(ctx, updateUserName, arg.ID, arg.Name)
	var i UpdateUserNameRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const upsertUserByEmail = `-- name: UpsertUserByEmail :one
INSERT INTO users (email) VALUES (lower($1::text))
ON CONFLICT ((lower(email))) WHERE deleted_at IS NULL DO UPDATE SET email = users.email
RETURNING id, email, name, created_at
`

type UpsertUserByEmailRow struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) UpsertUserByEmail(ctx context.Context, email string) (UpsertUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertUserByEmail, email)
	var i UpsertUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}
