// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: catalog.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCategories = `-- name: ListCategories :many
SELECT id, name, sort_order FROM categories ORDER BY sort_order, name
`

func (q *Queries) ListCategories(ctx context.Context) ([]Category, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(&i.ID, &i.Name, &i.SortOrder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCatalog = `-- name: SearchCatalog :many
SELECT ci.id, ci.name, ci.category_id, c.name AS category_name, ci.default_unit
FROM catalog_items ci
LEFT JOIN categories c ON c.id = ci.category_id
WHERE lower(ci.name) LIKE '%' || lower($1::text) || '%'
   OR word_similarity(lower($1::text), lower(ci.name)) > 0.4
ORDER BY (lower(ci.name) LIKE lower($1::text) || '%') DESC,
         word_similarity(lower($1::text), lower(ci.name)) DESC,
         ci.popularity DESC,
         ci.name
LIMIT $2
`

type SearchCatalogParams struct {
	Query      string `json:"query"`
	MaxResults int32  `json:"max_results"`
}

type SearchCatalogRow struct {
	ID           int32       `json:"id"`
	Name         string      `json:"name"`
	CategoryID   pgtype.Int4 `json:"category_id"`
	CategoryName pgtype.Text `json:"category_name"`
	DefaultUnit  pgtype.Text `json:"default_unit"`
}

// Поиск по справочнику: сначала совпадения по началу слова, потом похожие (с опечатками).
func (q *Queries) SearchCatalog(ctx context.Context, arg SearchCatalogParams) ([]SearchCatalogRow, error) {
	rows, err := q.db.Query(ctx, searchCatalog, arg.Query, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchCatalogRow
	for rows.Next() {
		var i SearchCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.CategoryID,
			&i.CategoryName,
			&i.DefaultUnit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
