// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const archiveBoughtItems = `-- name: ArchiveBoughtItems :execrows
INSERT INTO purchase_history (list_id, item_name, quantity, unit, price, bought_by, bought_at)
SELECT i.list_id, i.name, i.quantity, i.unit, i.price, i.bought_by, COALESCE(i.bought_at, now())
FROM items i WHERE i.list_id = $1 AND i.is_bought AND i.deleted_at IS NULL
`

func (q *Queries) ArchiveBoughtItems(ctx context.Context, listID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, archiveBoughtItems, listID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listItems = `-- name: ListItems :many
SELECT i.id, i.list_id, i.catalog_item_id, i.name, i.quantity, i.unit, i.price,
       i.category_id, i.is_bought, i.bought_by, i.bought_at, i.position, i.version, i.updated_at, (i.deleted_at IS NOT NULL)::bool AS deleted
FROM items i
WHERE i.list_id = $1
  AND i.version > $2::bigint
  AND (i.deleted_at IS NULL OR $3::bool)
ORDER BY i.version, i.position, i.id
`

type ListItemsParams struct {
	ListID         uuid.UUID `json:"list_id"`
	Since          int64     `json:"since"`
	IncludeDeleted bool      `json:"include_deleted"`
}

type ListItemsRow struct {
	ID            uuid.UUID          `json:"id"`
	ListID        uuid.UUID          `json:"list_id"`
	CatalogItemID pgtype.Int4        `json:"catalog_item_id"`
	Name          string             `json:"name"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          pgtype.Text        `json:"unit"`
	Price         pgtype.Numeric     `json:"price"`
	CategoryID    pgtype.Int4        `json:"category_id"`
	IsBought      bool               `json:"is_bought"`
	BoughtBy      uuid.NullUUID      `json:"bought_by"`
	BoughtAt      pgtype.Timestamptz `json:"bought_at"`
	Position      int32              `json:"position"`
	Version       int64              `json:"version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Deleted       bool               `json:"deleted"`
}

func (q *Queries) ListItems(ctx context.Context, arg ListItemsParams) ([]ListItemsRow, error) {
	rows, err := q.db.Query(ctx, listItems, arg.ListID, arg.Since, arg.IncludeDeleted)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListItemsRow
	for rows.Next() {
		var i ListItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.CatalogItemID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
			&i.Price,
			&i.CategoryID,
			&i.IsBought,
			&i.BoughtBy,
			&i.BoughtAt,
			&i.Position,
			&i.Version,
			&i.UpdatedAt,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextItemVersion = `-- name: NextItemVersion :one
UPDATE lists SET item_seq = item_seq + 1, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
RETURNING item_seq
`

// Занимает следующую версию списка и блокирует его строку до конца транзакции.
func (q *Queries) NextItemVersion(ctx context.Context, id uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, nextItemVersion, id)
	var item_seq int64
	err := row.Scan(&item_seq)
	return item_seq, err
}

const patchItem = `-- name: PatchItem :one
UPDATE items i SET
    name        = CASE WHEN $1::bool THEN $2::text ELSE i.name END,
    quantity    = CASE WHEN $3::bool THEN $4::numeric ELSE i.quantity END,
    unit        = CASE WHEN $5::bool THEN $6::text ELSE i.unit END,
    price       = CASE WHEN $7::bool THEN $8::numeric ELSE i.price END,
    category_id = CASE WHEN $9::bool THEN $10::int ELSE i.category_id END,
    position    = CASE WHEN $11::bool THEN $12::int ELSE i.position END,
    is_bought   = CASE WHEN $13::bool THEN $14::bool ELSE i.is_bought END,
    bought_by   = CASE WHEN NOT $13::bool THEN i.bought_by
                       WHEN NOT $14::bool THEN NULL
                       WHEN i.is_bought THEN i.bought_by
                       ELSE $15::uuid END,
    bought_at   = CASE WHEN NOT $13::bool THEN i.bought_at
                       WHEN NOT $14::bool THEN NULL
                       WHEN i.is_bought THEN i.bought_at
                       ELSE now() END,
    version     = $16,
    updated_at  = now()
WHERE i.id = $17 AND i.list_id = $18 AND i.deleted_at IS NULL
RETURNING i.id, i.list_id, i.catalog_item_id, i.name, i.quantity, i.unit, i.price,
       i.category_id, i.is_bought, i.bought_by, i.bought_at, i.position, i.version, i.updated_at, (i.deleted_at IS NOT NULL)::bool AS deleted
`

type PatchItemParams struct {
	SetName       bool           `json:"set_name"`
	Name          string         `json:"name"`
	SetQuantity   bool           `json:"set_quantity"`
	Quantity      pgtype.Numeric `json:"quantity"`
	SetUnit       bool           `json:"set_unit"`
	Unit          pgtype.Text    `json:"unit"`
	SetPrice      bool           `json:"set_price"`
	Price         pgtype.Numeric `json:"price"`
	SetCategoryID bool           `json:"set_category_id"`
	CategoryID    pgtype.Int4    `json:"category_id"`
	SetPosition   bool           `json:"set_position"`
	Position      int32          `json:"position"`
	SetBought     bool           `json:"set_bought"`
	IsBought      bool           `json:"is_bought"`
	Actor         uuid.UUID      `json:"actor"`
	Version       int64          `json:"version"`
	ID            uuid.UUID      `json:"id"`
	ListID        uuid.UUID      `json:"list_id"`
}

type PatchItemRow struct {
	ID            uuid.UUID          `json:"id"`
	ListID        uuid.UUID          `json:"list_id"`
	CatalogItemID pgtype.Int4        `json:"catalog_item_id"`
	Name          string             `json:"name"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          pgtype.Text        `json:"unit"`
	Price         pgtype.Numeric     `json:"price"`
	CategoryID    pgtype.Int4        `json:"category_id"`
	IsBought      bool               `json:"is_bought"`
	BoughtBy      uuid.NullUUID      `json:"bought_by"`
	BoughtAt      pgtype.Timestamptz `json:"bought_at"`
	Position      int32              `json:"position"`
	Version       int64              `json:"version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Deleted       bool               `json:"deleted"`
}

// Меняет только поля, для которых set_* = true (иначе клиент не может отличить «не менять» от «очистить»).
func (q *Queries) PatchItem(ctx context.Context, arg PatchItemParams) (PatchItemRow, error) {
	row := q.db.QueryRow(ctx, patchItem,
		arg.SetName,
		arg.Name,
		arg.SetQuantity,
		arg.Quantity,
		arg.SetUnit,
		arg.Unit,
		arg.SetPrice,
		arg.Price,
		arg.SetCategoryID,
		arg.CategoryID,
		arg.SetPosition,
		arg.Position,
		arg.SetBought,
		arg.IsBought,
		arg.Actor,
		arg.Version,
		arg.ID,
		arg.ListID,
	)
	var i PatchItemRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.CatalogItemID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Price,
		&i.CategoryID,
		&i.IsBought,
		&i.BoughtBy,
		&i.BoughtAt,
		&i.Position,
		&i.Version,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}

const softDeleteBoughtItems = `-- name: SoftDeleteBoughtItems :execrows
UPDATE items SET deleted_at = now(), version = $2, updated_at = now()
WHERE list_id = $1 AND is_bought AND deleted_at IS NULL
`

type SoftDeleteBoughtItemsParams struct {
	ListID  uuid.UUID `json:"list_id"`
	Version int64     `json:"version"`
}

func (q *Queries) SoftDeleteBoughtItems(ctx context.Context, arg SoftDeleteBoughtItemsParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBoughtItems, arg.ListID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteItem = `-- name: SoftDeleteItem :execrows
UPDATE items SET deleted_at = now(), version = $3, updated_at = now()
WHERE id = $1 AND list_id = $2 AND deleted_at IS NULL
`

type SoftDeleteItemParams struct {
	ID      uuid.UUID `json:"id"`
	ListID  uuid.UUID `json:"list_id"`
	Version int64     `json:"version"`
}

func (q *Queries) SoftDeleteItem(ctx context.Context, arg SoftDeleteItemParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteItem, arg.ID, arg.ListID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertItem = `-- name: UpsertItem :one
INSERT INTO items AS i (id, list_id, catalog_item_id, name, quantity, unit, price, category_id,
                        is_bought, bought_by, bought_at, position, created_by, version)
VALUES ($1, $2, $3, $4, $5::numeric,
        $6, $7::numeric, $8,
        $9::bool,
        CASE WHEN $9::bool THEN $10::uuid END,
        CASE WHEN $9::bool THEN now() END,
        $11, $10::uuid, $12)
ON CONFLICT (id) DO UPDATE SET
    catalog_item_id = EXCLUDED.catalog_item_id,
    name = EXCLUDED.name,
    quantity = EXCLUDED.quantity,
    unit = EXCLUDED.unit,
    price = EXCLUDED.price,
    category_id = EXCLUDED.category_id,
    is_bought = EXCLUDED.is_bought,
    bought_by = CASE WHEN EXCLUDED.is_bought THEN COALESCE(CASE WHEN i.is_bought THEN i.bought_by END, EXCLUDED.bought_by) END,
    bought_at = CASE WHEN EXCLUDED.is_bought THEN COALESCE(CASE WHEN i.is_bought THEN i.bought_at END, EXCLUDED.bought_at) END,
    position = EXCLUDED.position,
    version = EXCLUDED.version,
    updated_at = now()
WHERE i.list_id = EXCLUDED.list_id AND i.deleted_at IS NULL
RETURNING i.id, i.list_id, i.catalog_item_id, i.name, i.quantity, i.unit, i.price,
       i.category_id, i.is_bought, i.bought_by, i.bought_at, i.position, i.version, i.updated_at, (i.deleted_at IS NOT NULL)::bool AS deleted
`

type UpsertItemParams struct {
	ID            uuid.UUID      `json:"id"`
	ListID        uuid.UUID      `json:"list_id"`
	CatalogItemID pgtype.Int4    `json:"catalog_item_id"`
	Name          string         `json:"name"`
	Quantity      pgtype.Numeric `json:"quantity"`
	Unit          pgtype.Text    `json:"unit"`
	Price         pgtype.Numeric `json:"price"`
	CategoryID    pgtype.Int4    `json:"category_id"`
	IsBought      bool           `json:"is_bought"`
	Actor         uuid.UUID      `json:"actor"`
	Position      int32          `json:"position"`
	Version       int64          `json:"version"`
}

type UpsertItemRow struct {
	ID            uuid.UUID          `json:"id"`
	ListID        uuid.UUID          `json:"list_id"`
	CatalogItemID pgtype.Int4        `json:"catalog_item_id"`
	Name          string             `json:"name"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          pgtype.Text        `json:"unit"`
	Price         pgtype.Numeric     `json:"price"`
	CategoryID    pgtype.Int4        `json:"category_id"`
	IsBought      bool               `json:"is_bought"`
	BoughtBy      uuid.NullUUID      `json:"bought_by"`
	BoughtAt      pgtype.Timestamptz `json:"bought_at"`
	Position      int32              `json:"position"`
	Version       int64              `json:"version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	Deleted       bool               `json:"deleted"`
}

// Создаёт позицию с id от клиента или заменяет её. Позицию из другого списка или уже удалённую не трогает
// (тогда строки в ответе нет), поэтому по чужому id нельзя перехватить чужую позицию.
func (q *Queries) UpsertItem(ctx context.Context, arg UpsertItemParams) (UpsertItemRow, error) {
	row := q.db.QueryRow(ctx, upsertItem,
		arg.ID,
		arg.ListID,
		arg.CatalogItemID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Price,
		arg.CategoryID,
		arg.IsBought,
		arg.Actor,
		arg.Position,
		arg.Version,
	)
	var i UpsertItemRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.CatalogItemID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Price,
		&i.CategoryID,
		&i.IsBought,
		&i.BoughtBy,
		&i.BoughtAt,
		&i.Position,
		&i.Version,
		&i.UpdatedAt,
		&i.Deleted,
	)
	return i, err
}
