// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lists.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addListMember = `-- name: AddListMember :exec
INSERT INTO list_members (list_id, user_id, role) VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddListMemberParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
	Role   string    `json:"role"`
}

func (q *Queries) AddListMember(ctx context.Context, arg AddListMemberParams) error {
	_, err := q.db.Exec(ctx, addListMember, arg.ListID, arg.UserID, arg.Role)
	return err
}

const countListMembers = `-- name: CountListMembers :one
SELECT count(*)::int FROM list_members WHERE list_id = $1
`

func (q *Queries) CountListMembers(ctx context.Context, listID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countListMembers, listID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createInvite = `-- name: CreateInvite :one
INSERT INTO invites (list_id, code, created_by, expires_at, max_uses)
VALUES ($1, $2, $3, $4, $5)
RETURNING code, expires_at, max_uses, uses
`

type CreateInviteParams struct {
	ListID    uuid.UUID          `json:"list_id"`
	Code      string             `json:"code"`
	CreatedBy uuid.UUID          `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
}

type CreateInviteRow struct {
	Code      string             `json:"code"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	Uses      int32              `json:"uses"`
}

func (q *Queries) CreateInvite(ctx context.Context, arg CreateInviteParams) (CreateInviteRow, error) {
	row := q.db.QueryRow(ctx, createInvite,
		arg.ListID,
		arg.Code,
		arg.CreatedBy,
		arg.ExpiresAt,
		arg.MaxUses,
	)
	var i CreateInviteRow
	err := row.Scan(
		&i.Code,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const createList = `-- name: CreateList :one
INSERT INTO lists (title, owner_id) VALUES ($1, $2)
RETURNING id, title, owner_id, created_at, updated_at
`

type CreateListParams struct {
	Title   string    `json:"title"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type CreateListRow struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateList(ctx context.Context, arg CreateListParams) (CreateListRow, error) {
	row := q.db.QueryRow(ctx, createList, arg.Title, arg.OwnerID)
	var i CreateListRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createListWithID = `-- name: CreateListWithID :one
INSERT INTO lists (id, title, owner_id) VALUES ($1, $2, $3)
ON CONFLICT (id) DO NOTHING
RETURNING id, title, owner_id, created_at, updated_at
`

type CreateListWithIDParams struct {
	ID      uuid.UUID `json:"id"`
	Title   string    `json:"title"`
	OwnerID uuid.UUID `json:"owner_id"`
}

type CreateListWithIDRow struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateListWithID(ctx context.Context, arg CreateListWithIDParams) (CreateListWithIDRow, error) {
	row := q.db.QueryRow(ctx, createListWithID, arg.ID, arg.Title, arg.OwnerID)
	var i CreateListWithIDRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInviteByCodeForUpdate = `-- name: GetInviteByCodeForUpdate :one
SELECT i.id, i.list_id, i.expires_at, i.max_uses, i.uses
FROM invites i
JOIN lists l ON l.id = i.list_id AND l.deleted_at IS NULL
WHERE i.code = $1
FOR UPDATE OF i
`

type GetInviteByCodeForUpdateRow struct {
	ID        uuid.UUID          `json:"id"`
	ListID    uuid.UUID          `json:"list_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	Uses      int32              `json:"uses"`
}

func (q *Queries) GetInviteByCodeForUpdate(ctx context.Context, code string) (GetInviteByCodeForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getInviteByCodeForUpdate, code)
	var i GetInviteByCodeForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.ExpiresAt,
		&i.MaxUses,
		&i.Uses,
	)
	return i, err
}

const getListForMember = `-- name: GetListForMember :one
SELECT l.id, l.title, l.owner_id, l.created_at, l.updated_at, lm.role,
       (SELECT count(*) FROM list_members m WHERE m.list_id = l.id)::int AS member_count
FROM lists l
JOIN list_members lm ON lm.list_id = l.id AND lm.user_id = $1
WHERE l.id = $2 AND l.deleted_at IS NULL
`

type GetListForMemberParams struct {
	UserID uuid.UUID `json:"user_id"`
	ListID uuid.UUID `json:"list_id"`
}

type GetListForMemberRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Role        string             `json:"role"`
	MemberCount int32              `json:"member_count"`
}

func (q *Queries) GetListForMember(ctx context.Context, arg GetListForMemberParams) (GetListForMemberRow, error) {
	row := q.db.QueryRow(ctx, getListForMember, arg.UserID, arg.ListID)
	var i GetListForMemberRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Role,
		&i.MemberCount,
	)
	return i, err
}

const incrementInviteUses = `-- name: IncrementInviteUses :exec
UPDATE invites SET uses = uses + 1 WHERE id = $1
`

func (q *Queries) IncrementInviteUses(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementInviteUses, id)
	return err
}

const isActiveListMember = `-- name: IsActiveListMember :one
SELECT EXISTS (
    SELECT 1 FROM list_members lm JOIN lists l ON l.id = lm.list_id AND l.deleted_at IS NULL
    WHERE lm.list_id = $1 AND lm.user_id = $2
)
`

type IsActiveListMemberParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsActiveListMember(ctx context.Context, arg IsActiveListMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isActiveListMember, arg.ListID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const isListMember = `-- name: IsListMember :one
SELECT EXISTS (SELECT 1 FROM list_members WHERE list_id = $1 AND user_id = $2)
`

type IsListMemberParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) IsListMember(ctx context.Context, arg IsListMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isListMember, arg.ListID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listListsForUser = `-- name: ListListsForUser :many
SELECT l.id, l.title, l.owner_id, l.created_at, l.updated_at, lm.role,
       (SELECT count(*) FROM list_members m WHERE m.list_id = l.id)::int AS member_count
FROM lists l
JOIN list_members lm ON lm.list_id = l.id AND lm.user_id = $1
WHERE l.deleted_at IS NULL
ORDER BY l.updated_at DESC, l.created_at DESC
`

type ListListsForUserRow struct {
	ID          uuid.UUID          `json:"id"`
	Title       string             `json:"title"`
	OwnerID     uuid.UUID          `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Role        string             `json:"role"`
	MemberCount int32              `json:"member_count"`
}

func (q *Queries) ListListsForUser(ctx context.Context, userID uuid.UUID) ([]ListListsForUserRow, error) {
	rows, err := q.db.Query(ctx, listListsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListsForUserRow
	for rows.Next() {
		var i ListListsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Role,
			&i.MemberCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberIDs = `-- name: ListMemberIDs :many
SELECT user_id FROM list_members WHERE list_id = $1
`

func (q *Queries) ListMemberIDs(ctx context.Context, listID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listMemberIDs, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMembers = `-- name: ListMembers :many
SELECT u.id AS user_id, u.name, u.username, lm.role, lm.joined_at
FROM list_members lm
JOIN users u ON u.id = lm.user_id
WHERE lm.list_id = $1
ORDER BY lm.joined_at, u.id
`

type ListMembersRow struct {
	UserID   uuid.UUID          `json:"user_id"`
	Name     string             `json:"name"`
	Username string             `json:"username"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListMembers(ctx context.Context, listID uuid.UUID) ([]ListMembersRow, error) {
	rows, err := q.db.Query(ctx, listMembers, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMembersRow
	for rows.Next() {
		var i ListMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeListMember = `-- name: RemoveListMember :execrows
DELETE FROM list_members WHERE list_id = $1 AND user_id = $2 AND role <> 'owner'
`

type RemoveListMemberParams struct {
	ListID uuid.UUID `json:"list_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveListMember(ctx context.Context, arg RemoveListMemberParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeListMember, arg.ListID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameList = `-- name: RenameList :exec
UPDATE lists SET title = $2, updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

type RenameListParams struct {
	ID    uuid.UUID `json:"id"`
	Title string    `json:"title"`
}

func (q *Queries) RenameList(ctx context.Context, arg RenameListParams) error {
	_, err := q.db.Exec(ctx, renameList, arg.ID, arg.Title)
	return err
}

const softDeleteList = `-- name: SoftDeleteList :exec
UPDATE lists SET deleted_at = now(), updated_at = now() WHERE id = $1
`

func (q *Queries) SoftDeleteList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, softDeleteList, id)
	return err
}

const touchList = `-- name: TouchList :exec
UPDATE lists SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchList(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchList, id)
	return err
}
