// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AuthIdentity struct {
	UserID      uuid.UUID `json:"user_id"`
	Provider    string    `json:"provider"`
	ProviderUid string    `json:"provider_uid"`
}

type CatalogItem struct {
	ID          int32       `json:"id"`
	Name        string      `json:"name"`
	CategoryID  pgtype.Int4 `json:"category_id"`
	DefaultUnit pgtype.Text `json:"default_unit"`
	Popularity  int32       `json:"popularity"`
}

type Category struct {
	ID        int32  `json:"id"`
	Name      string `json:"name"`
	SortOrder int32  `json:"sort_order"`
}

type Device struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	ExpoPushToken string             `json:"expo_push_token"`
	Platform      string             `json:"platform"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Invite struct {
	ID        uuid.UUID          `json:"id"`
	ListID    uuid.UUID          `json:"list_id"`
	Code      string             `json:"code"`
	CreatedBy uuid.UUID          `json:"created_by"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	MaxUses   int32              `json:"max_uses"`
	Uses      int32              `json:"uses"`
}

type Item struct {
	ID            uuid.UUID          `json:"id"`
	ListID        uuid.UUID          `json:"list_id"`
	CatalogItemID pgtype.Int4        `json:"catalog_item_id"`
	Name          string             `json:"name"`
	Quantity      pgtype.Numeric     `json:"quantity"`
	Unit          pgtype.Text        `json:"unit"`
	Price         pgtype.Numeric     `json:"price"`
	CategoryID    pgtype.Int4        `json:"category_id"`
	IsBought      bool               `json:"is_bought"`
	BoughtBy      uuid.NullUUID      `json:"bought_by"`
	BoughtAt      pgtype.Timestamptz `json:"bought_at"`
	Position      int32              `json:"position"`
	CreatedBy     uuid.NullUUID      `json:"created_by"`
	Version       int64              `json:"version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type List struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	OwnerID   uuid.UUID          `json:"owner_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
	ItemSeq   int64              `json:"item_seq"`
}

type ListMember struct {
	ListID   uuid.UUID          `json:"list_id"`
	UserID   uuid.UUID          `json:"user_id"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type LoginCode struct {
	ID        int64              `json:"id"`
	Email     string             `json:"email"`
	CodeHash  string             `json:"code_hash"`
	Attempts  int32              `json:"attempts"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PurchaseHistory struct {
	ID       int64              `json:"id"`
	ListID   uuid.UUID          `json:"list_id"`
	ItemName string             `json:"item_name"`
	Quantity pgtype.Numeric     `json:"quantity"`
	Unit     pgtype.Text        `json:"unit"`
	Price    pgtype.Numeric     `json:"price"`
	BoughtBy uuid.NullUUID      `json:"bought_by"`
	BoughtAt pgtype.Timestamptz `json:"bought_at"`
}

type RefreshToken struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Unit struct {
	Code string `json:"code"`
	Name string `json:"name"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}
