// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: push.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const countUnboughtItems = `-- name: CountUnboughtItems :one
SELECT count(*)::int FROM items WHERE list_id = $1 AND NOT is_bought AND deleted_at IS NULL
`

func (q *Queries) CountUnboughtItems(ctx context.Context, listID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countUnboughtItems, listID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE FROM devices WHERE expo_push_token = $1
`

func (q *Queries) DeleteDeviceByToken(ctx context.Context, expoPushToken string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, expoPushToken)
	return err
}

const deleteUserDevice = `-- name: DeleteUserDevice :execrows
DELETE FROM devices WHERE expo_push_token = $1 AND user_id = $2
`

type DeleteUserDeviceParams struct {
	ExpoPushToken string    `json:"expo_push_token"`
	UserID        uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteUserDevice(ctx context.Context, arg DeleteUserDeviceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserDevice, arg.ExpoPushToken, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getListTitle = `-- name: GetListTitle :one
SELECT title FROM lists WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetListTitle(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getListTitle, id)
	var title string
	err := row.Scan(&title)
	return title, err
}

const getUserName = `-- name: GetUserName :one
SELECT name FROM users WHERE id = $1
`

func (q *Queries) GetUserName(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getUserName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const itemExists = `-- name: ItemExists :one
SELECT EXISTS (SELECT 1 FROM items WHERE id = $1)
`

func (q *Queries) ItemExists(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, itemExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const itemIsBought = `-- name: ItemIsBought :one
SELECT is_bought FROM items WHERE id = $1 AND list_id = $2 AND deleted_at IS NULL
`

type ItemIsBoughtParams struct {
	ID     uuid.UUID `json:"id"`
	ListID uuid.UUID `json:"list_id"`
}

func (q *Queries) ItemIsBought(ctx context.Context, arg ItemIsBoughtParams) (bool, error) {
	row := q.db.QueryRow(ctx, itemIsBought, arg.ID, arg.ListID)
	var is_bought bool
	err := row.Scan(&is_bought)
	return is_bought, err
}

const listDevicesForUsers = `-- name: ListDevicesForUsers :many
SELECT user_id, expo_push_token FROM devices WHERE user_id = ANY($1::uuid[])
`

type ListDevicesForUsersRow struct {
	UserID        uuid.UUID `json:"user_id"`
	ExpoPushToken string    `json:"expo_push_token"`
}

func (q *Queries) ListDevicesForUsers(ctx context.Context, userIds []uuid.UUID) ([]ListDevicesForUsersRow, error) {
	rows, err := q.db.Query(ctx, listDevicesForUsers, userIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDevicesForUsersRow
	for rows.Next() {
		var i ListDevicesForUsersRow
		if err := rows.Scan(&i.UserID, &i.ExpoPushToken); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimUserDevices = `-- name: TrimUserDevices :exec
DELETE FROM devices WHERE id IN (
    SELECT d.id FROM devices d WHERE d.user_id = $1 ORDER BY d.updated_at DESC, d.id OFFSET 20
)
`

// Оставляет у пользователя не больше 20 самых свежих устройств.
func (q *Queries) TrimUserDevices(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, trimUserDevices, userID)
	return err
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO devices (user_id, expo_push_token, platform) VALUES ($1, $2, $3)
ON CONFLICT (expo_push_token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform, updated_at = now()
`

type UpsertDeviceParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ExpoPushToken string    `json:"expo_push_token"`
	Platform      string    `json:"platform"`
}

// Токен уникален: если устройство перешло к другому пользователю, оно переписывается на него.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice, arg.UserID, arg.ExpoPushToken, arg.Platform)
	return err
}
