// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: realtime.sql

package store

import (
	"context"
)

const notify = `-- name: Notify :exec
SELECT pg_notify('list_changes', $1::text)
`

// Рассылка через Postgres LISTEN/NOTIFY: в транзакции доставляется только после коммита.
func (q *Queries) Notify(ctx context.Context, payload string) error {
	_, err := q.db.Exec(ctx, notify, payload)
	return err
}
